# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
    # build the official release
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "-t"
          - "gcr.io/$PROJECT_ID/ns:latest"
          - "."
    # make sure the image works
    - name: "gcr.io/$PROJECT_ID/ns:latest"
      args:
          - "version"
    # build the head from source
    - name: "gcr.io/cloud-builders/git"
      args:
          - "clone"
          - "-b"
          - "main"
          - "https://github.com/namespacelabs/foundation.git"
    - name: "golang"
      dir: "foundation"
      args:
          - "go"
          - "build"
          - "-v"
          - "-o"
          - "cmd/ns/ns"
          - "cmd/ns/main.go"
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "-f"
          - "Dockerfile.head"
          - "-t"
          - "gcr.io/$PROJECT_ID/ns:head"
          - "."

images:
    - "gcr.io/$PROJECT_ID/ns:latest"
    - "gcr.io/$PROJECT_ID/ns:head"
